main = ".open-next/worker.js"
name = "mtg-plot-gen"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "prod-mtg-cards"
database_id = "156ab131-22d4-49ba-90c8-64730f41beb4"

[observability]
enabled = true
